import { getCookie } from "cookies-next";
import Head from "next/head";
import InterestMarker from "~/components/InterestMarker";
import Footer from "~/components/Layout/Footer";
import Header from "~/components/Layout/Header";

import { api } from "~/utils/api";

export default function Home() {
  // const { data } = api.post.hello.useQuery({ text: "from tRPC" });

  const user = JSON.parse(getCookie("userDetails") || "{}");
  const { data: currentUserDetails } = api.auth.getCurrentUser.useQuery({
    email: user.email,
  });

  const { data: interests } = api.category.getAll.useQuery();

  console.log({ currentUserDetails, interests });
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <main className="my-10 flex flex-col items-center justify-center">
        <InterestMarker data={interests || []} />
      </main>
      <Footer />
    </>
  );
}
